apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudshell-manager-binding
  namespace: cloudshell
subjects:
  - kind: ServiceAccount
    name: cloudshell-sa
    namespace: cloudshell
roleRef:
  kind: Role
  name: cloudshell-manager
  apiGroup: rbac.authorization.k8s.io