auth:
  username: rabbitmq
  password: rabbitmq

image:
  debug: true

extraEnvVars:
  - name: RABBITMQ_LOGS
    value: "-"
  - name: RABBITMQ_LOG_LEVEL
    value: "debug"

persistence:
  enabled: true
  storageClass: "rabbitmq-storage"
  accessModes:
    - ReadWriteOnce
