auth:
  username: rabbitmq
  password: rabbitmq

image:
  debug: true

clustering:
  enabled: false

extraConfiguration: |-
  vm_memory_high_watermark.relative = 0.8

extraEnvVars:
  - name: RABBITMQ_LOGS
    value: "-"
  - name: RABBITMQ_LOG_LEVEL
    value: "debug"

persistence:
  enabled: true
  storageClass: "rabbitmq-storage"
  accessModes:
    - ReadWriteOnce
