{{- if and .Values.vault.enabled (or (eq .Values.vault.integration.mode "csi") (eq .Values.vault.integration.mode "hybrid")) .Values.vault.integration.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.vault.integration.csi.secretProviderClass.name | default "vault-gok-agent-provider" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: agent-backend
    chart: {{ include "agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  provider: vault
  parameters:
    roleName: "{{ .Values.vault.integration.csi.role }}"
    vaultAddress: "{{ .Values.vault.address }}"
    {{- if .Values.vault.integration.csi.vaultNamespace }}
    vaultNamespace: "{{ .Values.vault.integration.csi.vaultNamespace }}"
    {{- end }}
    objects: |
      {{- range .Values.vault.integration.csi.secrets }}
      - objectName: "{{ .objectName }}"
        secretPath: "{{ .secretPath }}"
        secretKey: "{{ .secretKey }}"
      {{- end }}
  {{- if .Values.vault.integration.csi.secretObjects }}
  secretObjects:
  {{- range .Values.vault.integration.csi.secretObjects }}
  - secretName: {{ .secretName }}
    type: {{ .type | default "Opaque" }}
    data:
    {{- range .data }}
    - objectName: {{ .objectName }}
      key: {{ .key }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}