apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-controller
  template:
    metadata:
      labels:
        app: web-controller
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "web-controller"
        vault.hashicorp.com/agent-inject-secret-web-controller: "secret/data/web-controller"
        vault.hashicorp.com/agent-inject-template-web-controller: |
          {{- printf "{\"jwt-secret\": \"{{ .Data.data.jwt-secret }}\", \"api-token\": \"{{ .Data.data.api-token }}\"}" }}
    spec:
      serviceAccountName: web-controller-sa
      containers:
        - name: api
          image: "{{ .Values.image.api }}"
          env:
            - name: VAULT_SECRETS_PATH
              value: "/vault/secrets"
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmqHost }}"
          volumeMounts:
            - name: vault-secrets
              mountPath: /vault/secrets
              readOnly: true
        - name: frontend
          image: "{{ .Values.image.frontend }}"
          ports:
            - containerPort: 3000
      volumes:
        - name: vault-secrets
          emptyDir: {}