apiVersion: v1
kind: Service
metadata:
  name: {{ template "ldapclient2.fullname" . }}
  labels:
    app: {{ template "ldapclient2.name" . }}
    chart: {{ template "ldapclient2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  #type: {{ .Values.service.type }}
  clusterIP: None
{{- if .Values.service.ports }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
{{- end }}
  selector:
    app: {{ template "ldapclient2.name" . }}
    release: {{ .Release.Name }}
