replicaCount: 1

image:
  repository: registry.gokcloud.com/console
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: console.gokcloud.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  OAUTH_ISSUER: "https://keycloak.gokcloud.com/realms/GokDevelopers"
  OAUTH_CLIENT_ID: "gok-developers-client"