apiVersion: v1
kind: Service
metadata:
  name: {{ template "dockerhook.fullname" . }}
  labels:
    app: {{ template "dockerhook.name" . }}
    chart: {{ template "dockerhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
#  clusterIP: None
  ports:
  - port: 5002
    protocol: TCP
    name: ui
  selector:
    app: {{ template "dockerhook.name" . }}
    release: {{ .Release.Name }}
