extraEnvVars:
  - name: LOG_LEVEL
    value: debug
  - name: OAUTH2_PROXY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth2-proxy-secrets
        key: clientSecret
  - name: OAUTH2_PROXY_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: oauth2-proxy-config
        key: clientID

configuration:
  clientID: ${OAUTH2_PROXY_CLIENT_ID}
  clientSecretFile: /etc/secrets/clientSecret
  cookieSecret: mycookiesumit123
  oidcIssuerUrl: https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/auth
  redirectUrl: kube*.

global:
  storageClass: "oauth-storage"

extraVolumes:
  - name: secrets
    secret:
      secretName: oauth2-proxy-secrets

extraVolumeMounts:
  - name: secrets
    mountPath: /etc/secrets
    readOnly: true