extraEnvVars:
  - name: LOG_LEVEL
    value: debug
  - name: OAUTH2_PROXY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth-secrets
        key: OIDC_CLIENT_SECRET
  - name: OAUTH2_PROXY_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: oauth2-proxy-config
        key: clientID
  - name: OAUTH2_OIDC_ISSUER_URL
    valueFrom:
      configMapKeyRef:
        name: oauth2-proxy-config
        key: oidcIssuerUrl
  - name: OAUTH2_REDIRECT_URL
    valueFrom:
      configMapKeyRef:
        name: oauth2-proxy-config
        key: oidcIssuerUrl

configuration:
  clientID: ${OAUTH2_PROXY_CLIENT_ID}
  clientSecretFile: /etc/secrets/OIDC_CLIENT_SECRET
  cookieSecret: mycookiesumit123
  oidcIssuerUrl: $(OAUTH2_OIDC_ISSUER_URL)
  redirectUrl: $(OAUTH2_REDIRECT_URL)

global:
  storageClass: "oauth-storage"

extraVolumes:
  - name: secrets
    secret:
      secretName: oauth-secrets

extraVolumeMounts:
  - name: secrets
    mountPath: /etc/secrets
    readOnly: true