extraEnvVars:
  - name: LOG_LEVEL
    value: debug

configuration:
  clientID: gok-developers-client
  clientSecret: sC1hHm9c2qHjwYtfumcQnEwyH7NOqkaV
  cookieSecret: mycookiesumit123
  oidcIssuerUrl: https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/auth
  redirectUrl: kube*.

global:
  storageClass: "oauth-storage"

extraArgs:
  - "--provider=keycloak"
  - "--login-url=https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/auth"
  - "--redeem-url=https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/token"
  - "--profile-url=https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/userinfo"
  - "--validate-url=https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/userinfo"
  - "--keycloak-group=groups"
  - "--scope=openid email profile groups"