apiVersion: v1
kind: Service
metadata:
  name: web-controller
  labels:
    app: web-controller
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      name: http
  selector:
    app: web-controller