replicaCount: 1
image:
  api: registry.gokcloud.com/gok-controller:latest
  frontend: yourrepo/web-controller-frontend:latest

rabbitmqHost: rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cloud.uat

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: web-controller.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - web-controller.example.com
      secretName: web-controller-tls

vault:
  enabled: true
  agentInjector: true
  role: "web-controller"
  secretPath: "secret/data/web-controller"

oidc:
  issuer: https://keycloak.gokcloud.com/realms/GokDevelopers
  clientId: gok-developers-client
  requiredRole: administrators