replicaCount: 1
image:
  api: registry.gokcloud.com/web-controller:latest

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: web-controller.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - web-controller.example.com
      secretName: web-controller-tls

vault:
  enabled: true
  agentInjector: true
  role: "web-controller"
  secretPath: "secret/web-controller"

oidc:
  issuer: https://keycloak.gokcloud.com/realms/GokDevelopers
  clientId: gok-developers-client
  requiredGroup: administrators

rabbitmq:
  host: rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cloud.uat
  user: rabbitmq
  password: rabbitmq