apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ttyd.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ttyd.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ttyd.name" . }}
    spec:
      serviceAccountName: ttyd-admin
      volumes:
        - name: tools
          emptyDir: {}
      initContainers:
        - name: install-tools
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              set -ex
              apk update
              apk add --no-cache curl bash docker-cli openssl file
              # Install kubectl
              KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
              curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
              if ! file kubectl | grep -q 'ELF'; then
                echo "kubectl download failed!"
                exit 1
              fi
              install -m 755 kubectl /tools/kubectl
              # Install helm
              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
              mv /usr/local/bin/helm /tools/helm
              # Copy docker client
              cp /usr/bin/docker /tools/docker
          volumeMounts:
            - name: tools
              mountPath: /tools
      containers:
        - name: ttyd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ttyd"]
          args: ["-W", "bash"]
          ports:
            - containerPort: 7681
          env:
            - name: PATH
              value: "/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tools
              mountPath: /tools