apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttyd.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7681
      protocol: TCP
      name: http
  selector:
    app: {{ include "ttyd.name" . }}