apiServer:
  certSANs:
  - "master.cloud.com"
  - "11.0.0.1"
  extraArgs:
    authorization-mode: Node,RBAC
    service-node-port-range: 30000-32767
    #Below 2 properties causing issue
#    authorization-rbac-super-user: admin
#    admission-control: NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,ResourceQuota
    enable-swagger-ui: "true"
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: ${CLUSTER_NAME}
controllerManager:
  extraArgs:
    attach-detach-reconcile-sync-period: 1m0s
    configure-cloud-routes: "false"
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
controlPlaneEndpoint: ${LOAD_BALANCER_URL}
kind: ClusterConfiguration
kubernetesVersion: v1.23.6
networking:
  dnsDomain: ${DNS_DOMAIN}
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler:
  extraArgs:
    logtostderr: "true"