apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
clusterName: ${CLUSTER_NAME}
apiServer:
  certSANs:
  - "master.cloud.com"
  - "${MASTER_HOST_IP}"
  extraArgs:
    authorization-mode: Node,RBAC
    service-node-port-range: 80-32767
    oidc-issuer-url: ${OIDC_ISSUE_URL}
    oidc-client-id: ${OIDC_CLIENT_ID}
    oidc-username-claim: ${OIDC_USERNAME_CLAIM}
    oidc-groups-claim: ${OIDC_GROUPS_CLAIM}
    oidc-ca-file: /usr/local/share/ca-certificates/issuer.crt
#    enable-swagger-ui: "true"
  timeoutForControlPlane: 4m0s
controllerManager:
  extraArgs:
    attach-detach-reconcile-sync-period: 1m0s
    configure-cloud-routes: "false"
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
controlPlaneEndpoint: ${LOAD_BALANCER_URL}
kubernetesVersion: v1.32.0
networking:
  dnsDomain: ${DNS_DOMAIN}
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/12

---

kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: "systemd"