apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: __USERNAME__-csr
spec:
  groups:
    - system:authenticated
    - cloud:masters
  request: __CSRREQUEST__
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - digital signature
    - key encipherment
    - client auth
