debug:
  enabled: true
hub:
  extraConfig:
    disableSSLVerification: |
      import ssl
      from tornado.httpclient import AsyncHTTPClient
      from tornado.curl_httpclient import CurlAsyncHTTPClient

      # Disable SSL verification globally
      ssl_ctx = ssl.create_default_context()
      ssl_ctx.check_hostname = False
      ssl_ctx.verify_mode = ssl.CERT_NONE
      AsyncHTTPClient.configure(CurlAsyncHTTPClient, defaults=dict(ssl_options=ssl_ctx))
  extraEnv:
    OAUTH2_TLS_VERIFY: "false"
    CURL_CA_BUNDLE: ""
    REQUESTS_CA_BUNDLE: ""
  db:
    type: sqlite-pvc
    pvc:
      storageClassName: "jupyter-storage"
      accessModes:
        - ReadWriteOnce
      storage: 1Gi

singleuser:
  storage:
    dynamic:
      storageClass: "jupyter-user-storage"
    capacity: 2Gi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  ingressClassName: "nginx"
  hosts:
   - master.cloud.com
  pathType: ImplementationSpecific
  tls:
   - secretName: appingress-certificate
     hosts:
       - master.cloud.com
