configs:
  secret:
    extra:
      oidc.keycloak.clientSecret: "abcdef"
  cm:
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.cloud.com/realms/master
      clientID: GokDevelopers
      clientSecret: $oidc.keycloak.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email
server:
  ingress:
    enabled: true
    pathType: ImplementationSpecific
    ingressClassName: "nginx"
    hostname: master.cloud.com
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      kubernetes.io/ingress.class: nginx
      kubernetes.io/ingress.allow-http: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
