apiVersion: v1
kind: Service
metadata:
  name: {{ template "githook.fullname" . }}
  labels:
    app: {{ template "githook.name" . }}
    chart: {{ template "githook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
#  clusterIP: None
  ports:
  - port: 5001
    protocol: TCP
    name: ui
    #nodePort: 32501
  selector:
    app: {{ template "githook.name" . }}
    release: {{ .Release.Name }}
