apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-conf
  namespace: ingress
  labels:
    app: nginx-ingress-lb
data:
  enable-vts-status: 'true'
  ssl-dh-param: "ingress/lb-dhparam"
