apiVersion: v1
kind: Service
metadata:
  name: {{ template "kerberos.fullname" . }}
  labels:
    app: {{ template "kerberos.name" . }}
    chart: {{ template "kerberos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
#  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - port: 88
    protocol: UDP
    name: krb1
  - port: 749
    protocol: TCP
    name: krb2
  - port: 750
    protocol: TCP
    name: krb3
  - port: 22
    protocol: TCP
    name: ssh22
  - port: 2122
    protocol: TCP
    name: ssh2122
  - port: 636
    protocol: TCP
    name: ssl-ldap  
  selector:
    app: {{ template "kerberos.name" . }}
    release: {{ .Release.Name }}
