hub:
  config:
    GenericOAuthenticator:
      validate_server_cert: false
      scope:
        - openid
        - profile
        - email
        - sub
        - groups
    cull:
      enabled: false
      timeout: 3600
      every: 600
      users:
        - skmaji1
        - admin
    # JupyterHub:
    #   base_url: /hub/
  db:
    type: sqlite-pvc
    pvc:
      storageClassName: "gok-cloud-shell-storage"
      accessModes:
        - ReadWriteOnce
      storage: 1Gi

singleuser:
  image:
    name: registry.gokcloud.com/ttyd
    tag: latest
    pullSecrets:
      - gokcloud-regcred
  cmd: ["/usr/local/bin/ttyd", "-p","7681", "-W", "bash"]
  defaultUrl: "/proxy/7681/"
  storage:
    dynamic:
      storageClass: "gok-cloud-shell-user-storage"
    capacity: 2Gi

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  ingressClassName: "nginx"
  hosts:
   - master.cloud.com
  pathType: ImplementationSpecific
  tls:
   - secretName: appingress-certificate
     hosts:
       - master.cloud.com
