server:
  ha:
    enabled: false

  # Enable persistence
  dataStorage:
    enabled: true
    storageClass: vault-storage
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    existingClaim: vault-pvc
    mountPath: /vault/data

  auditStorage:
    enabled: false

  # Annotations for the ingress
  ingress:
    enabled: true
    ingressClassName: "nginx"
    
    hosts:
      - host: vault.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: vault-tls
        hosts:
          - vault.example.com

ui:
  enabled: true

