apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
spec:
  template:
    spec:
      initContainers:
        - name: vault-unseal
          image: registry.gokcloud.com/vault-with-tools:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Unsealing Vault..."
              export VAULT_ADDR=http://vault.vault.svc.cloud.uat:8200
              for key in $(kubectl get secret vault-init-keys -n vault -o jsonpath='{.data.vault-init\.json}' | base64 -d | jq -r '.unseal_keys_b64[]'); do
                vault operator unseal $key
              done
              echo "Vault is unsealed."
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cloud.uat:8200"