apiVersion: v1
kind: Service
metadata:
  name: {{ template "reghook.fullname" . }}
  labels:
    app: {{ template "reghook.name" . }}
    chart: {{ template "reghook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
#  clusterIP: None
  ports:
  - port: 5003
    protocol: TCP
    name: ui
  selector:
    app: {{ template "reghook.name" . }}
    release: {{ .Release.Name }}
