envFromSecret: kube-prometheus-stack-grafana-oauth
extraConfigmapMounts:
  - name: keycloak-configmap
    mountPath: /etc/ssl/certs/keycloak.crt
    subPath: keycloak.crt
    configMap: certs-configmap
    readOnly: true
#  - name: issuer-configmap
#    mountPath: /etc/ssl/certs/issuer.crt
#    subPath: issuer.crt
#    configMap: certs-configmap
#    readOnly: true

#adminUser: admin
#adminPassword: admin
grafana.ini:
  auth.generic_oauth:
    name: Keycloak-OAuth
    enabled: true
    client_id: $__env{GF_AUTH_KEYCLOAK_CLIENT_ID}
    client_secret: $__env{GF_AUTH_KEYCLOAK_CLIENT_SECRET}
    scopes: openid profile offline_access groups
    auth_url: https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/auth
    token_url: https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/token
    api_url: https://keycloak.gokcloud.com/realms/GokDevelopers/protocol/openid-connect/userinfo
    allowed_domains: gokcloud.com
#    email_attribute_path: email
    login_attribute_path: preferred_username
    name_attribute_path: given_name
    allow_sign_up: true
    role_attribute_path: contains(roles[*], 'administrators') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
  server:
    domain: kube.gokcloud.com
    root_url: https://kube.gokcloud.com/grafana
ingress:
  enabled: true
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  ingressClassName: nginx
  # Values can be templated
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  labels: {}
  path: /grafana(/|$)(.*)

  # pathType is only for k8s >= 1.1=
  pathType: ImplementationSpecific

  hosts:
    - master.cloud.com
  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation
  ## Or for k8s > 1.19
  # - path: /*
  #   pathType: Prefix
  #   backend:
  #     service:
  #       name: ssl-redirect
  #       port:
  #         name: use-annotation


  tls:
    - secretName: appingress-certificate
      hosts:
        - master.cloud.com
