# Default values for __APPNAME__.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: master.cloud.com:5000/__APPNAME__
  tag: latest
  pullPolicy: Always
  port: __PORT__

service:
  type: ClusterIP
  port: __PORT__

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /__CONTEXT__
  hosts:
    - master.cloud.com
  tls:
    - secretName: appingress-certificate
      hosts:
        - master.cloud.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
