replicaCount: 1

image:
  repository: registry.gokcloud.com/cloudshell
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: cloudshell.gokcloud.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
resources: {}