# --- Keycloak naming configuration ---
fullnameOverride: "keycloak"
nameOverride: "keycloak"

# --- Keycloak image & startup (upstream image) ---
image:
  repository: quay.io/keycloak/keycloak
  # Pin to a version you want; the chart's appVersion is fine, but explicit is better
  tag: "26.0.7"
  pullPolicy: IfNotPresentKeycloak image & startup (upstream image) ---
image:
  repository: quay.io/keycloak/keycloak
  # Pin to a version you want; the chart’s appVersion is fine, but explicit is better
  tag: "26.0.7"
  pullPolicy: IfNotPresent

# Use the Quarkus KC launcher; you can add more args if needed (build, cache, etc.)
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"                 # for production use 'start' (not start-dev)
  - "--http-enabled=true"
  - "--http-port=8080"

# Environment variables (codecentric/keycloakx format)
extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: admin-user
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: admin-password
  - name: KC_HOSTNAME
    value: "placeholder"
  - name: KC_PROXY
    value: "edge"
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KC_DB_PASSWORD
    value: "sumit"
  - name: KC_CACHE
    value: "local"


# Use existing secret for admin credentials (codecentric/keycloakx)
existingSecret: keycloak-secrets

# Replicas & resources (tune as you like)
replicas: 1

# --- HTTP configuration to use root path instead of /auth ---
http:
  relativePath: "/"

# --- Ingress configuration for codecentric/keycloakx ---
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "placeholder"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: keycloak-tls
      hosts:
        - "{{ .Values.ingress.hostname }}"

# --- Database configuration for codecentric/keycloakx ---
database:
  vendor: postgres
  hostname: keycloak-postgresql
  port: 5432
  database: keycloak
  username: postgres
  # Password will be set via existing secret

# Using external PostgreSQL deployment - no subchart needed
postgresql:
  enabled: false

# Optional: service settings
service:
  type: ClusterIP
  port: 8080
