variant: opensearch
env:
  - name: "FLUENTD_CONF"
    value: "../../../etc/fluent/fluent.conf"
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: FLUENT_OPENSEARCH_HOST
    value: "opensearch-logging"
  - name:  FLUENT_OPENSEARCH_PORT
    value: "9200"
  - name: FLUENT_OPENSEARCH_SCHEME
    value: "https"
  # Option to configure OpenSearch plugin with self signed certs
  # ================================================================
  - name: FLUENT_OPENSEARCH_SSL_VERIFY
    value: "true"
  # Option to configure OpenSearch plugin with tls
  # ================================================================
  - name: FLUENT_OPENSEARCH_SSL_VERSION
    value: "TLSv1_2"
  # Authentication
  # =====================
  - name: FLUENT_OPENSEARCH_USER
    value: "username"
  - name: FLUENT_OPENSEARCH_PASSWORD
    value: "changeme"
  # Certificate
  # =====================
  - name: FLUENT_OPENSEARCH_CA_PATH
    value: "/path/to/file.ca"
  - name: FLUENT_OPENSEARCH_CLIENT_CERT
    value: "/path/to/file.cert"
  - name: FLUENT_OPENSEARCH_CLIENT_KEY
    value: "/path/to/file.key"
  - name: FLUENT_OPENSEARCH_CLIENT_KEY_PASS
    value: "changeme"
  # Fluentd Parser
  # =====================
  - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
    value: "cri"
  - name: FLUENT_CONTAINER_TAIL_PARSER_TIME_FORMAT
    value: "%Y-%m-%dT%H:%M:%S.%N%:z"
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: master.cloud.com
      port: 24231
  tls:
   - secretName: appingress-certificate
     hosts:
       - master.cloud.com
