apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-controller
  labels:
    app: web-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-controller
  template:
    metadata:
      labels:
        app: web-controller
      {{- if .Values.vault.enabled }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/agent-inject-secret-web-controller: "{{ .Values.vault.secretPath }}"
        vault.hashicorp.com/agent-inject-template-web-controller: |
          {{- printf "{\"api-token\": \"{{ .Data.data.api-token }}\"}" }}
      {{- end }}
    spec:
      serviceAccountName: web-controller-sa
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret | default "regcred" }}
      containers:
        - name: api
          image: "{{ .Values.image.api }}"
          env:
            - name: VAULT_SECRETS_PATH
              value: "/vault/secrets"
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmqHost }}"
            - name: OAUTH_ISSUER
              value: "{{ .Values.oidc.issuer }}"
            - name: OAUTH_CLIENT_ID
              value: "{{ .Values.oidc.clientId }}"
            - name: REQUIRED_ROLE
              value: "{{ .Values.oidc.requiredRole }}"
          volumeMounts:
            - name: vault-secrets
              mountPath: /vault/secrets
              readOnly: true
        - name: frontend
          image: "{{ .Values.image.frontend }}"
          ports:
            - containerPort: 3000
      volumes:
        - name: vault-secrets
          emptyDir: {}