{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-controller
  labels:
    app: web-controller
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
      
        paths:
          - path: /controller
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-controller
                port:
                  number: 8080
    {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-controller-socket
  labels:
    app: web-controller
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /controller/socket.io/
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-controller
                port:
                  number: 8080
    {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}


{{- end }}