apiVersion: v1
kind: Secret
metadata:
  name: krbsecret
type: Opaque
data:
  password: {{ .Values.kerberos.password | b64enc | quote }}
  kdcpassword: {{ .Values.kerberos.kdcpassword | b64enc | quote }}
  admpassword: {{ .Values.kerberos.admpassword | b64enc | quote }}