apiVersion: v1
kind: Service
metadata:
  name: {{ template "ldap.fullname" . }}
  labels:
    app: {{ template "ldap.name" . }}
    chart: {{ template "ldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
#  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - port: 8181
    protocol: TCP
    name: ui
  - port: 389
    protocol: TCP
    name: search
  - port: 22
    protocol: TCP
    name: ssh22
  - port: 2122
    protocol: TCP
    name: ssh2122
  - port: 636
    protocol: TCP
    name: ssl-tcp
  - port: 636
    protocol: UDP
    name: ssl-udp  
  selector:
    app: {{ template "ldap.name" . }}
    release: {{ .Release.Name }}
