replicaCount: 1

image:
  repository: registry.gokcloud.com/agent
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  name: agent-backend-sa

env:
  OAUTH_ISSUER: "https://keycloak.gokcloud.com/realms/GokDevelopers"
  OAUTH_CLIENT_ID: "gok-developers-client"
  REQUIRED_ROLE: "administrators"
  RABBITMQ_HOST: "rabbitmq.rabbitmq"
  # RabbitMQ credentials (optional - will be retrieved from Kubernetes secret if not provided)
  # RABBITMQ_USER: "custom-user"
  # RABBITMQ_PASSWORD: "custom-password"