apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "console.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "console.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret | default "regcred" }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              value: "1"