apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "console.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "console.name" . }}
    spec:
      volumes:
        - name: ca-cert
          configMap:
            name: ca-cert
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret | default "regcred" }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: REQUESTS_CA_BUNDLE
              value: /usr/local/share/ca-certificates/issuer.crt
            - name: OAUTH_ISSUER
              value: {{ .Values.env.OAUTH_ISSUER | quote }}
            - name: OAUTH_CLIENT_ID
              value: {{ .Values.env.OAUTH_CLIENT_ID | quote }}
          volumeMounts:
            - name: ca-cert
              mountPath: /usr/local/share/ca-certificates/issuer.crt
              subPath: issuer.crt