kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
- kind: User
  name: admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
