#!/bin/bash

# GOK Show Commands Feature - Quick Reference and Examples

echo "============================================"
echo "GOK Show Commands Feature - Quick Reference"
echo "============================================"
echo ""

echo "BASIC USAGE:"
echo "------------"
echo "# Install with command display"
echo "  ./gok-new install <component> --show-commands"
echo ""
echo "# Reset with command display"
echo "  ./gok-new reset <component> --show-commands"
echo ""

echo "PRACTICAL EXAMPLES:"
echo "-------------------"
echo "# Docker installation (shows all Docker setup commands)"
echo "  ./gok-new install docker --show-commands"
echo ""
echo "# LDAP installation (shows build, deploy, and configuration commands)"
echo "  ./gok-new install ldap --show-commands"
echo ""
echo "# Kubernetes installation (shows kubeadm, kubectl, and network commands)"
echo "  ./gok-new install kubernetes --show-commands"
echo ""
echo "# Reset with command visibility"
echo "  ./gok-new reset monitoring --show-commands"
echo ""

echo "COMBINING WITH OTHER FLAGS:"
echo "---------------------------"
echo "# Show commands + verbose logging"
echo "  ./gok-new install helm --show-commands --verbose"
echo ""
echo "# Show commands + quiet mode (minimal logging)"
echo "  ./gok-new install cert-manager --show-commands --quiet"
echo ""
echo "# Show commands + skip updates"
echo "  ./gok-new install prometheus --show-commands --skip-update"
echo ""

echo "ENVIRONMENT VARIABLE METHOD:"
echo "----------------------------"
echo "# Set globally for all commands"
echo "  export GOK_SHOW_COMMANDS=true"
echo "  ./gok-new install argocd"
echo ""
echo "# One-time for single command"
echo "  GOK_SHOW_COMMANDS=true ./gok-new install jenkins"
echo ""

echo "WHAT YOU'LL SEE:"
echo "----------------"
echo "When enabled, each command is logged before execution:"
echo ""
echo "  ℹ Executing: kubectl create namespace ldap"
echo "  ℹ Executing: helm repo add prometheus-community https://..."
echo "  ℹ Executing: docker build -t myimage:latest ."
echo "  ℹ Executing: systemctl restart docker"
echo ""

echo "AUTOMATIC ACTIVATION:"
echo "---------------------"
echo "The feature auto-activates with verbose mode:"
echo "  ./gok-new install docker --verbose  # Also shows commands"
echo ""

echo "============================================"
echo "Feature Status: ✅ FULLY IMPLEMENTED"
echo "============================================"
echo ""
echo "For detailed documentation, see:"
echo "  docs/SHOW_COMMANDS_FEATURE.md"
echo ""
