ingress:
  enabled: true
  className: nginx
  path: /
  # Used to create an Ingress record.
  hosts:
    - master.cloud.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  labels: {}
  tls:
    - secretName: appingress-certificate
      hosts:
        - master.cloud.com