ingress:
  enabled: true
  className: nginx
  path: /
  # Used to create an Ingress record.
  hosts:
    - master.cloud.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # As its uploading docker image it body size need to be increased.
    # https://github.com/kubernetes/ingress-nginx/issues/4825
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  labels: {}
  tls:
    - secretName: appingress-certificate
      hosts:
        - master.cloud.com