apiVersion: v1
kind: Service
metadata:
  name: mq
  labels:
    app: mq
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
      protocol: TCP
      name: management
  selector:
    app: mq