apiVersion: v1
kind: Service
metadata:
  name: gok-controller
  labels:
    app: gok-controller
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    app: gok-controller