{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "gok-controller" }}
  labels:
    app: gok-controller
    component: controller
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name | default "gok-agent" }}-vault-auth
  labels:
    app: gok-controller
    component: authentication
rules:
{{- with .Values.rbac.rules }}
{{- toYaml . | nindent 0 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name | default "gok-agent" }}-vault-auth
  labels:
    app: gok-controller
    component: authentication
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name | default "gok-agent" }}-vault-auth
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default "gok-agent" }}
  namespace: {{ .Release.Namespace }}
{{- end }}